spring.application.name=demo

spring.datasource.url=jdbc:oracle:thin:@//10.11.10.68:1521/trainingdb
spring.datasource.username=training_trungnt
spring.datasource.password=training_trungnt#123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.datasource.url=jdbc:mysql://localhost:3307/ten_database_cua_ban?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# C?u hình JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update


#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
