spring.application.name=demo

spring.datasource.url=jdbc:oracle:thin:@//10.11.10.68:1521/trainingdb
spring.datasource.username=training_trungnt
spring.datasource.password=training_trungnt#123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.datasource.url=jdbc:mysql://localhost:3307/ten_database_cua_ban?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# C?u hình JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update


#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
# JWT Configuration
jwt.secret=gbrYVii0QAIXeQ6trE8kjcQjdzB9OGkUiwyaMk7akru0RBU7M0ArFojaVF046w6sWtMFYT7PsgU9WqQ/tSeC7TwS+5YJdThX0GwL7htOkN/imA5mnEOfiLYstGN0a6rCI1EQKzJo+HK6X/7KV/qEYd3E0ehH1gQbcemFMw2SMp/AgwfCKAz5RkWhta66YjJtYfYPcA+j/3K4UY1UqiAp1qy7PngA30Zzk9A6O65wiXHo5whouwtPhs4oh18Vh3zai6pq12Mz+sSjgKzOul3nlGlXu55AGfYa8MeqaX4v59FYiZwsHYHVNmLgKZBA7x6Mu0jWOIw7kL9KaG7UCGJ1wQ==
jwt.expiration=3600000

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=60000

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000
spring.cache.redis.cache-null-values=false
